# Generated by Django 3.2.11 on 2022-02-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('Migration_TypeId', models.CharField(max_length=50)),
                ('Level', models.CharField(blank=True, choices=[('Programlevel', 'programlevel'), ('Statementlevel', 'statementlevel')], max_length=50, null=True)),
                ('Version_Id', models.SmallIntegerField(default=0)),
                ('Feature_Version', models.SmallIntegerField(default=0)),
                ('Object_Type', models.CharField(max_length=50)),
                ('Feature_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Feature_Name', models.CharField(max_length=100, unique=True)),
                ('Sequence', models.CharField(max_length=50)),
                ('Source_FeatureDescription', models.TextField(blank=True, null=True)),
                ('Source_Code', models.TextField(blank=True, null=True)),
                ('Conversion_Code', models.TextField(blank=True, null=True)),
                ('Target_FeatureDescription', models.TextField(blank=True, null=True)),
                ('Target_Expected_Output', models.TextField(blank=True, null=True)),
                ('Target_ActualCode', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttachmentType', models.CharField(blank=True, choices=[('Sourcedescription', 'sourcedescription'), ('Targetdescription', 'targetdescription'), ('Conversion', 'conversion'), ('Sourcecode', 'sourcecode'), ('Actualtargetcode', 'actualtargetcode'), ('Expectedconversion', 'expectedconversion')], max_length=50, null=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('Feature_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FeatureApp.feature')),
            ],
        ),
    ]
