# Generated by Django 3.2.11 on 2022-02-11 12:18

import FeatureApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to=FeatureApp.models.user_directory_path),
        ),
    ]
