# Generated by Django 3.2.11 on 2022-02-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(max_length=100)),
                ('Object_Type', models.CharField(max_length=100)),
                ('Feature_Name', models.CharField(max_length=100)),
                ('Approval_Status', models.CharField(max_length=100)),
                ('Access_Type', models.CharField(max_length=100)),
                ('Start_Date', models.DateTimeField(null=True)),
                ('End_Date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Migration_TypeId', models.CharField(max_length=50, null=True, unique=True)),
                ('Object_Type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
