# Generated by Django 3.2.11 on 2022-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='can_view',
            field=models.TextField(default='{{"Label": "Procedures","subMenu": []},{"Label": "Functions","subMenu": []},{"Label": "Packages","subMenu": []},{"Label": "Indexes","subMenu": []},{"Label": "Materialized views", "subMenu": []}}'),
        ),
    ]
