# Generated by Django 3.2.11 on 2022-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0002_users_can_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='can_view',
        ),
    ]
