# Generated by Django 3.2.11 on 2022-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0002_approvals_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrations',
            name='Migration_TypeId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
