# Generated by Django 3.2.11 on 2022-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='Start_Date',
            new_name='Created_at',
        ),
        migrations.AlterField(
            model_name='approvals',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
