# Generated by Django 3.2.11 on 2022-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='Start_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='Start_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
