# Generated by Django 3.2.11 on 2022-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Migration_TypeId', models.CharField(max_length=100, null=True)),
                ('Deploy_Start_Time', models.DateTimeField(blank=True, null=True)),
                ('Deploy_End_Time', models.DateTimeField(blank=True, null=True)),
                ('Deployment_Status', models.CharField(default='Deploy in Progress', max_length=50)),
            ],
        ),
    ]
