# Generated by Django 3.2.11 on 2022-03-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0002_auto_20220309_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='modified_date',
            new_name='Expiry_date',
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='Start_Date',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='permissions',
            old_name='End_Date',
            new_name='Expiry_date',
        ),
    ]
