# Generated by Django 3.2.11 on 2022-03-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0002_auto_20220329_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='Project_Version_Id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachments',
            name='Feature_Version_Id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachments',
            name='Project_Version_Id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrations',
            name='Project_Version_Id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='permissions',
            name='Project_Version_Id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
