# Generated by Django 3.2.11 on 2022-05-17 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0002_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='Feature_Created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='Feature_Created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Last_Modified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Last_Modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
