# Generated by Django 3.2.11 on 2022-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0003_auto_20220309_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='Expiry_date',
            field=models.DateField(null=True),
        ),
    ]
