# Generated by Django 3.2.11 on 2022-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0003_auto_20220517_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='Feature_Requested_By',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Feature_Requested_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
