# Generated by Django 3.2.11 on 2022-03-30 14:35

import FeatureApp.models
import FeatureApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0003_auto_20220330_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='Request_Create_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Request_Modified_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='Expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='Attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=FeatureApp.storage.CleanFileNameStorage(), upload_to=FeatureApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Feature_version_approval_status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
