# Generated by Django 3.2.11 on 2022-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0004_auto_20220330_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='Request_Create_Date',
        ),
    ]
