# Generated by Django 3.2.11 on 2022-03-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0004_alter_permissions_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='Expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
