# Generated by Django 3.2.11 on 2022-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0005_alter_permissions_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin_migrations',
            field=models.TextField(null=True),
        ),
    ]
