# Generated by Django 3.2.11 on 2022-03-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0005_remove_feature_request_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='Request_Modified_Date',
            new_name='Feature_Approval_Date',
        ),
    ]
