# Generated by Django 3.2.11 on 2022-03-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeatureApp', '0006_users_admin_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='Approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
